### ISSUE TITLE
\subsection 格式和目录问题

### ISSUE THREAD

**Issue by geyuuu** [qianchd/NKU_thesis_graduate#1]
感谢作者的整理！我目前主要使用的是来自[NewFuture/NKThesis](https://github.com/NewFuture/NKThesis)的模板
目前两个版本都存在一些明显的问题，希望能修改一下造福后人。

## subsection格式问题
`\subsection`的格式是2024标准中的模式一（阿拉伯数字），其他部分的格式是模式二（中文数字），但是2024标准要求不能混用两种模式。我建议使用重新定义的如下格式：
```
\def\thesubsection{\CJKnumber{\arabic{subsection}}、\hspace{-1em}}
```
我不太懂如何处理顿号和subsection标题之间一个字符的间距，所以用`\hspace{-1em}`去除，应该有更好的处理方式。

## 目录格式问题
此外您这个版本的目录缩进明显过大了，也没有展开到subsection级别。原始作者中自定义了一个复杂的宏`\NKT@dottedline`来处理各级目录格式，但实际使用中缩进不正常我也没看懂是如何处理的。我把`\tocsectionindent`和`\tocsubsectionindent`的值都调成非标准的值满足标准的要求，这里也应该是有更好的解决方案。
```
% 不知道怎么调它本身的缩进，只能用负数凑合一下了
\def\tocsectionindent{0.5em}
\def\tocsubsectionindent{-2.5em}
```

[NewFuture/NKThesis](https://github.com/NewFuture/NKThesis)的解决方案是在NKThesis.cfg文件开头强行重定义了目录格式覆盖了NKThesis.sty中的设置，这样有点过于简单粗暴，导致前面关于字体的设置等全部无效了。
```
\renewcommand*\l@section{\@dottedtocline{1}{1em}{3.5em}}
\renewcommand*\l@subsection{\@dottedtocline{1}{2em}{2.5em}}
```
但是话说回来，孙老师这个模板定义`\NKT@dottedline`这些复杂的宏确实有点炫技了，用一些已有的宏对之后的维护更友好一点。

## 参考文献问题
您这个版本使用的biblatex后端是bibtex，我使用[zotero-better-bibtex](https://github.com/retorquere/zotero-better-bibtex)导出的`.bib`文件就难以使用了，还是希望能使用biber作为后端。

我这些解决方案都不完美，就不pull了。您这个版本能被官方钦定肯定用的人会比较多，如果能让官方组织一个学生小组解决一下历史遗留问题，用一些更易用的宏包，定能造福后人。

比如一个学弟用ctex重写的模板：[NKUThesis](https://github.com/tensor-matrix/NKUThesis)

**Comment by qianchd** [comment]
您的建议很好，如果南开有tex社团定期做这一方面的更新是最好的，目前基本就是ad-hoc的土办法。目前的repo只是在23年学校提供的模板上对“修改授权书”和“原创性声明”进行了相应更新，其他部分基本保持了不变，因此也提供给了图书馆作为原版本的更新。

toc层级的修改应是在“NKThesis.cfg”文件的第一行通过修改\tocdepth变量来实现；关于引用文献原模板中提供了三种方案，也包括了natbib的方案，更多的支持欢迎提交pr。**这些个性化的需求其实更重要的是恰当的文档支持。**

关于目录缩进这里没有改动过，目前的老模板下目测是按两个上级中文字符大小进行缩进的，即使展开到subsection也还够用，所以没有新的强制规范下还是沿用旧代码比较保险，个性化的修改我本身也无法判断恰当与否。

我刚注意到新标准中关于章节名的要求，讲道理目前的逻辑更易读一些，但应该按新标准修改一下，也欢迎pr解决这个问题。

**Comment by qianchd** [comment]
> 我刚注意到新标准中关于章节名的要求，讲道理目前的逻辑更易读一些。目前如果直接修改的话，对小节的交叉引用会有问题，例如引用小节 \ref{subsub:3} 时会变成" 三、中说明了xxx"，原来的安排可以是"第3.3节说明了xxx"，这对数学类的论文是比较致命的问题，如果非要对着新标准，建议是全部用数字章节编号最方便。也欢迎pr解决这个问题。

修改了相应目录和标题模块的程序，目前测试了下应该是可以接受的版本，具体可以见首页说明。

**Comment by geyuuu** [comment]
👍
